#!/usr/bin/env bash

# Go up the directory tree until you arrive to the git root
while [ ! -d .git ]
do
  cd ../
done

#DON'T RUN THE TEST IF WE ARE IN CONTINUOUS_INTEGRATION ENV
if [ "$TRAVIS" = "true" ]; then
   exit 0
fi

# It is not propertly finding the changed files.
# TODO: Take a look to see why is failing
#files=$(git diff --name-only --diff-filter=ACM | grep "^src/\|test/.*js$")

#if [ "$files" = "" ]; then
#    exit 0
#fi

pass=true
echo -e "Running Unit Tests: \c"

result="$(./node_modules/.bin/gulp test| grep "Error: 1")"

if [ "$result" = "" ]; then
     echo -e "\033[32mPassed\033[0m"
else
     echo -e "\033[31mFailed\033[0m"
     pass=false
fi

if ! $pass; then
    echo -e "\033[41mPUSH FAILED:\033[0m Your push contains failing tests. Please fix them and try again.\033[0m"
    exit 1
else
    echo -e "\033[42mPUSH SUCCEEDED\033[0m"
fi